# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'development'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'staging'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'development'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'staging'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'development'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']