on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 'google-github-actions/auth@v1'
      - uses: awalsh128/cache-apt-pkgs-action@v1
      - uses: actions/upload-artifact@v3
      - uses: actions/download-artifact@v3
      - uses: 'google-github-actions/deploy-cloudrun@v1'
